// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtlwawqkwslyvrfohnhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bHdhd3Frd3NseXZyZm9obmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDMwNTEsImV4cCI6MjA3Mjc3OTA1MX0.qIkZja6EQMt4x99LN8GaRgCS8rWnPvW2TT1NUbdy5Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});